/**
 * mintNFT.ts — Mint an OracleNodeNFT for your address
 *
 * Prerequisites:
 *   - keys.json generated by generateKeys.ts
 *   - Address funded with testnet BTC (≥ 100,000 sats recommended)
 *
 * Usage: node --import tsx/esm mintNFT.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';
import { JSONRpcProvider } from 'opnet';
import { TransactionFactory, Wallet, BinaryWriter } from '@btc-vision/transaction';
import { networks } from '@btc-vision/bitcoin';

const __dirname = dirname(fileURLToPath(import.meta.url));
const NETWORK   = (networks as any).opnetTestnet;
const RPC_URL   = process.env.OPNET_RPC_URL ?? 'https://testnet.opnet.org';
const NFT_ADDR  = process.env.NFT_CONTRACT  ?? 'opt1sqzchetuzymeewfkj8et2hvm2pkjg2ctpksm3mtun';

const keysFile = process.env.KEYS_FILE ?? join(__dirname, 'keys.json');
const keys     = JSON.parse(readFileSync(keysFile, 'utf-8'));
const wallet   = Wallet.fromWif(keys.schnorrPrivWIF, keys.quantumPrivHex, NETWORK);

console.log('[mint] Address:', wallet.p2tr);
console.log('[mint] NFT contract:', NFT_ADDR);

const provider = new JSONRpcProvider(RPC_URL, NETWORK, 60_000);
const factory  = new TransactionFactory();

// Fetch UTXOs
const r    = await fetch(`${RPC_URL}/api/v1/address/utxos?address=${wallet.p2tr}&optimize=true`);
const data = await r.json() as any;
const utxos = ((data.confirmed ?? []) as any[]).map((u: any) => ({
    transactionId: u.transactionId, outputIndex: u.outputIndex,
    value: BigInt(u.value), scriptPubKey: u.scriptPubKey,
}));

if (!utxos.length) {
    console.error('[mint] ❌ No UTXOs — fund your address first:', wallet.p2tr);
    console.error('[mint]    Testnet faucet: https://testnet.opnet.org');
    process.exit(1);
}
console.log('[mint] UTXOs:', utxos.length, '— total:', utxos.reduce((s: bigint, u: any) => s + u.value, 0n), 'sats');

// Build calldata: mint(address)
const selHash  = createHash('sha256').update('mint(address)').digest();
const selector = ((selHash[0] << 24) | (selHash[1] << 16) | (selHash[2] << 8) | selHash[3]) >>> 0;

const contractInfo = await provider.getPublicKeyInfo(NFT_ADDR, true).catch(() => null);
if (!contractInfo) {
    console.error('[mint] ❌ NFT contract not indexed');
    process.exit(1);
}

// Encode caller address as 30-byte address
const callerInfo = await provider.getPublicKeyInfo(wallet.p2tr, true);
const calldata   = new BinaryWriter();
calldata.writeSelector(selector);
calldata.writeBytes(Buffer.from(callerInfo.toHex(), 'hex'));

const challenge = await provider.getChallenge();
const result = await factory.signConsolidatedInteraction({
    signer: wallet.keypair, mldsaSigner: wallet.mldsaKeypair,
    network: NETWORK, from: wallet.p2tr,
    to: contractInfo.toHex(), contract: contractInfo.toHex(),
    calldata: calldata.getBuffer(), utxos, challenge,
    feeRate: 60, priorityFee: 0n, gasSatFee: 10000n,
});

const sr = await provider.sendRawTransaction(result.setupTransaction, false);
console.log('[mint] Setup:', sr.success ? '✅' : '❌', sr.result);
if (!sr.success) process.exit(1);

await new Promise(r => setTimeout(r, 4000));

const rr = await provider.sendRawTransaction(result.revealTransaction, false);
console.log('[mint] Reveal:', rr.success ? '✅' : '❌', rr.result);

if (rr.success) {
    console.log('');
    console.log('✅ NFT minted! txid:', result.revealTxId);
    console.log('');
    console.log('Wait for the tx to be indexed, then check your tokenId:');
    console.log(`  curl "${RPC_URL}/api/v1/address/tokens?address=${wallet.p2tr}"`);
    console.log('');
    console.log('Then register your node:');
    console.log('  node --import tsx/esm registerNode.ts --token <tokenId>');
}
