/**
 * registerNode.ts — Register your oracle node on-chain
 *
 * Prerequisites:
 *   - keys.json generated by generateKeys.ts
 *   - NFT minted (tokenId in keys.json after mintNFT.ts)
 *   - Address funded with testnet BTC
 *
 * Usage: node --import tsx/esm registerNode.ts --token <tokenId>
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { createHash } from 'crypto';
import { JSONRpcProvider } from 'opnet';
import { TransactionFactory, Wallet, BinaryWriter } from '@btc-vision/transaction';
import { networks } from '@btc-vision/bitcoin';

const __dirname  = dirname(fileURLToPath(import.meta.url));
const NETWORK    = (networks as any).opnetTestnet;
const RPC_URL    = process.env.OPNET_RPC_URL ?? 'https://testnet.opnet.org';
const REGISTRY   = process.env.REGISTRY_CONTRACT ?? 'opt1sqp0ce6tqqk3z4wwajgzufdm4vrwf234zjunljqkn';

// Parse tokenId argument
const tokenArgIdx = process.argv.indexOf('--token');
if (tokenArgIdx === -1) {
    console.error('Usage: node --import tsx/esm registerNode.ts --token <tokenId>');
    process.exit(1);
}
const tokenId = BigInt(process.argv[tokenArgIdx + 1]);

// Load keys
const keysFile = process.env.KEYS_FILE ?? join(__dirname, 'keys.json');
const keys     = JSON.parse(readFileSync(keysFile, 'utf-8'));
const wallet   = Wallet.fromWif(keys.schnorrPrivWIF, keys.quantumPrivHex, NETWORK);

console.log('[register] Node address:', wallet.p2tr);
console.log('[register] Token ID:', tokenId.toString());
console.log('[register] Schnorr pubkey:', keys.xOnlyPubHex);
console.log('[register] Registry:', REGISTRY);

const provider = new JSONRpcProvider(RPC_URL, NETWORK, 60_000);
const factory  = new TransactionFactory();

// Fetch UTXOs
const r    = await fetch(`${RPC_URL}/api/v1/address/utxos?address=${wallet.p2tr}&optimize=true`);
const data = await r.json() as any;
const utxos = ((data.confirmed ?? []) as any[]).map((u: any) => ({
    transactionId: u.transactionId, outputIndex: u.outputIndex,
    value: BigInt(u.value), scriptPubKey: u.scriptPubKey,
}));

if (!utxos.length) {
    console.error('[register] ❌ No UTXOs — fund your address first:', wallet.p2tr);
    process.exit(1);
}
console.log('[register] UTXOs:', utxos.length, '—', utxos.reduce((s: bigint, u: any) => s + u.value, 0n), 'sats');

// Build calldata: registerNode(tokenId, schnorrPubKey)
const selHash  = createHash('sha256').update('registerNode(uint256,uint256)').digest();
const selector = ((selHash[0] << 24) | (selHash[1] << 16) | (selHash[2] << 8) | selHash[3]) >>> 0;

const schnorrPubKeyU256 = BigInt('0x' + keys.xOnlyPubHex.padStart(64, '0'));

const calldata = new BinaryWriter();
calldata.writeSelector(selector);
calldata.writeU256(tokenId);
calldata.writeU256(schnorrPubKeyU256);

// Get contract pubkey info
const contractInfo = await provider.getPublicKeyInfo(REGISTRY, true).catch(() => null);
if (!contractInfo) {
    console.error('[register] ❌ Registry contract not indexed. Is it deployed?');
    process.exit(1);
}

const challenge = await provider.getChallenge();
const result = await factory.signConsolidatedInteraction({
    signer: wallet.keypair, mldsaSigner: wallet.mldsaKeypair,
    network: NETWORK, from: wallet.p2tr,
    to: contractInfo.toHex(), contract: contractInfo.toHex(),
    calldata: calldata.getBuffer(), utxos, challenge,
    feeRate: 60, priorityFee: 0n, gasSatFee: 10000n,
});

const sr = await provider.sendRawTransaction(result.setupTransaction, false);
console.log('[register] Setup:', sr.success ? '✅' : '❌', sr.result);
if (!sr.success) process.exit(1);

await new Promise(r => setTimeout(r, 4000));

const rr = await provider.sendRawTransaction(result.revealTransaction, false);
console.log('[register] Reveal:', rr.success ? '✅' : '❌', rr.result);

if (rr.success) {
    console.log('');
    console.log('✅ Node registered successfully!');
    console.log('  Token ID:', tokenId.toString());
    console.log('  Oracle key:', keys.xOnlyPubHex);
    console.log('  txid:', result.revealTxId);
    console.log('');
    console.log('Start your daemon:');
    console.log('  source node.env && node --import tsx/esm ../node/src/scripts/runDaemon.ts');
}
